extends CharacterBody2D


const SPEED = 130.0
const JUMP_VELOCITY = -300.0

@onready var animator = $AnimatedSprite2D

func _physics_process(delta: float) -> void:
	# Add the gravity.
	if not is_on_floor():
		velocity += get_gravity() * delta

	# Handle jump.
	if Input.is_action_just_pressed("ui_accept") and is_on_floor():
		velocity.y = JUMP_VELOCITY

	# Get the input direction and handle the movement/deceleration.
	# As good practice, you should replace UI actions with custom gameplay actions.
	var direction := Input.get_axis("ui_left", "ui_right")
	
	# animations
	if direction == 0:
		if animator.animation != "idle":
			animator.play("idle")
	else:
		if animator.animation != "run":
			animator.play("run")
		if direction > 0:
			animator.flip_h = false
		elif  direction < 0:
			animator.flip_h = true
	
	#if direction: 
		#velocity.x = direction * SPEED 
	#else: 
		#velocity.x = move_toward(velocity.x, 0, SPEED)
		
	const ACCEL = 800.0
	const FRICTION = 1000.0

	if direction != 0:
		velocity.x = move_toward(velocity.x, direction * SPEED, ACCEL * delta)
	else:
		velocity.x = move_toward(velocity.x, 0, FRICTION * delta)
	
	move_and_slide()
